### ISSUE TITLE
CharacterCreation.log() | Data handling bug.

### ISSUE THREAD

**Issue by aytimothy** [Ahsome/Guards-of-Aetheria#5]
Commit: 90b4969a477c12e46740de8cef0d63e5021eedc1
Branch: New-UI-Handling

**Bug:** When CharacterCreation.log() method is called upon, it does not move the array data correctly.

**Comment by somebody1234** [comment]
@aytimothy is this better?
(I did it in like 30 seconds as well :) )

**Comment by somebody1234** [comment]
Note: used A = B instead of B = A
