### ISSUE TITLE
CharacterCreation.cs | Skipping Stages 3-5

### ISSUE THREAD

**Issue by aytimothy** [Ahsome/Guards-of-Aetheria#6]
Commit: 5208d3091fd443234d08fa90e3c48ca525e62153

Bug: The character creation menu skips from Stage 2 (class select) to Stage 6 (the incomplete item giver and stuffs), without going through Stage 3-5 (race, attributes and confirmation).

Note: _Stage 6 does nothing because I haven't written the code for it yet... As in the method it calls does nothing._

**Comment by aytimothy** [comment]
Commit: cb32b09891c689aa55473b959d56718d972f9d97

Tempoary bug fix: Stage 6 goes straight back to Stage 4
Possible fix: Stage 4 then goes on to Stage 7 (but that's just long-winded)

Still looking for a possible fix.

**Comment by aytimothy** [comment]
Commit: 342b6fe6dad6aa7a50852842740e17807cb88ba8
Problem fixed.

Todo: Database debugger
Todo: Database test tools
Todo: Database editor (can't Lafamas just use MSAccess?)
Todo: More databases
Todo: Save format
Todo: Extra stuffs (the stage 6)

**Comment by somebody1234** [comment]
@aytimothy Can't we just use a database that VS has an editor for?
