### ISSUE TITLE
NullReferenceException!

### ISSUE THREAD

**Issue by mrfishie** [Ahsome/Guards-of-Aetheria#7]
After finishing 'testing the movement', the screen clears and a NullReferenceException is thrown and not handled.

Is it because there are no more possible paths after the movement test?

**Comment by Ahsome** [comment]
@mrfishie, Could you screenshot the error/exception?

**Comment by mrfishie** [comment]
Sure thing:
![Image](http://i.imgur.com/jIZDR2R.jpg)

**Comment by Ahsome** [comment]
I will have to reproduce the bug to see the error. Does this occur when you press **ENTER** after it shows that you passed testing the movement system?

**Comment by mrfishie** [comment]
It says 'test movement', you press **ENTER**, it says 'you have tested the movement successfully', you press **ENTER** again, and that is when this occurs.

**Comment by somebody1234** [comment]
@mrfishie I don't think it's that important, because in the final database there will be no references to nowhere. If you want, someone could make a project in GoA-Toolset to check for errors in the database.

**Comment by somebody1234** [comment]
It might be implemented at some time, but not anytime soon.
