### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by somebody1234** [Ahsome/Guards-of-Aetheria#8]
- [ ] GUI mode
- [ ] Screen resizing
- [ ] Colours
- [ ] Screen partitioning (WIP, untested, pending commit)
- [x] Extract Utility.cs to Improved.dll
- [ ] Make code more readable
- [ ] Beep/text alerts
- [ ] Finish item.cs
- [ ] Finish item database fields
- [ ] Finish scenario database fields
- [ ] HTML to console, plus finish frames

**Comment by Ahsome** [comment]
Shame, was excited about the changes

**Comment by Lafamas** [comment]
> Shame, was excited about the changes

Wait what? Whats this from the two most disappeared members of this group?
